services:
  # Backend API
  backend:
    image: ghcr.io/kasappeal/deita/backend:latest
    container_name: deita-backend
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://deita:${POSTGRES_PASSWORD}@postgres:5432/deita
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - FROM_EMAIL=${FROM_EMAIL}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=43200
      - ENVIRONMENT=production
      - DEBUG=false
      - APP_NAME=Deita
      - APP_VERSION=${APP_VERSION:-latest}
      - DUCKDB_PATH=/app/data/deita.duckdb
      - AI_MODEL_NAME=${AI_MODEL_NAME:-local-llm}
      - AI_MODEL_ENDPOINT=${AI_MODEL_ENDPOINT}
      - AI_MODEL_API_KEY=${AI_MODEL_API_KEY}
    volumes:
      - duckdb_data:/app/data
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend
  frontend:
    image: ghcr.io/kasappeal/deita/frontend:latest
    container_name: deita-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: deita-postgres
    environment:
      POSTGRES_DB: deita
      POSTGRES_USER: deita
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U deita -d deita"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
  duckdb_data:
    driver: local

networks:
  default:
    name: deita-network
