"""Add saved_queries table

Revision ID: 004_add_saved_queries
Revises: 003_add_files
Create Date: 2025-10-03 10:00:00.000000+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "004_add_saved_queries"
down_revision: Union[str, None] = "003_add_files"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "saved_queries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_saved_queries_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_saved_queries")),
    )
    op.create_index(op.f("ix_saved_queries_id"), "saved_queries", ["id"], unique=False)
    op.create_index(
        op.f("ix_saved_queries_workspace_id"), "saved_queries", ["workspace_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_saved_queries_workspace_id"), table_name="saved_queries")
    op.drop_index(op.f("ix_saved_queries_id"), table_name="saved_queries")
    op.drop_table("saved_queries")
    # ### end Alembic commands ###
