"""Add row_count column to files table

Revision ID: ffa3cc0330b3
Revises: 003_add_files
Create Date: 2025-10-03 09:57:07.354124+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ffa3cc0330b3"
down_revision: Union[str, None] = "003_add_files"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("files", sa.Column("row_count", sa.Integer(), nullable=False, server_default='0'))
    # Remove server default after adding column
    op.alter_column("files", "row_count", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("files", "row_count")
    # ### end Alembic commands ###
